### ISSUE TITLE
[BUG]: %s  Unsupported MIME type: image/x-icon

### ISSUE THREAD

**Issue by ruoruoji** [josh-hemphill/vite-plugin-favicon#14]
### Prerequisites

  * [ ] Reproduced the problem in a sandbox or repo: <https://codepen.io>
  * [ ] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Ajosh-hemphill/vite-plugin-favicon>

### Description

<img width="523" alt="image" src="https://user-images.githubusercontent.com/30526662/199715924-70f06c3b-1178-4c0b-b325-67282ccb6d56.png">

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions

|||
| --------- | --- |
| Platform: |     |
| Version:  |     |
| Editor(v):|     |
| OS:       |     |

**Comment by eimantaszlabys** [comment]
This bug will be solved soon or no? :)

**Comment by josh-hemphill** [comment]
It looks like it's an issue with the Jimp library; I've been trying to get around to a rewrite since the Jimp maintainers are not interested in supporting SVG and the favicon library is fundamentally problematic. So it probably won't be fixed until I get around to the rewrite.
